// 第二批候选公司：美国大型雇主与知名企业，用于继续发现自建（Workday 企业站）招聘系统。
export const EXTRA=`
Aflac,Allstate,Ameriprise,Aon,Arthur J Gallagher,Assurant,AIG,Chubb,Cincinnati Financial,CNA,
Erie Insurance,Guardian Life,Lincoln Financial,Loews,MassMutual,MetLife,Nationwide,New York Life,
Northwestern Mutual,Pacific Life,Principal Financial,Reinsurance Group,Sun Life,Unum,Voya,
Ally Financial,Citizens Financial,Comerica,Fifth Third,First Republic,Huntington Bancshares,KeyBank,
M&T Bank,Northern Trust,Raymond James,Regions Bank,Santander,SVB,Zions Bancorporation,BNY Mellon,
Franklin Templeton,Invesco,T Rowe Price,Janus Henderson,Neuberger Berman,PIMCO,Wellington Management,
Apollo Global Management,Blackstone,Carlyle Group,KKR,TPG,Ares Management,Brookfield,
Marsh McLennan,Willis Towers Watson,Alliant,Acrisure,
Cardinal Health,McKesson,Cencora,Henry Schein,Owens & Minor,Quest Diagnostics,Labcorp,IQVIA,
Charles River Laboratories,Catalent,West Pharmaceutical,Organon,Viatris,Teva,Sandoz,Perrigo,
Jazz Pharmaceuticals,Alnylam,BioMarin,Incyte,Neurocrine,Sarepta,United Therapeutics,Ionis,
Alkermes,Exelixis,Halozyme,Blueprint Medicines,Apellis,Karuna,Madrigal,Insmed,Axsome,
Molina Healthcare,Oscar,Bright Health,Devoted Health,Privia Health,Oak Street Health,One Medical,
Encompass Health,Tenet Healthcare,Universal Health Services,Community Health Systems,DaVita,Fresenius,
Cleveland Clinic,Mayo Clinic,Johns Hopkins Medicine,Mass General Brigham,Northwell Health,
Providence Health,Sutter Health,Intermountain Health,Advocate Health,Trinity Health,CommonSpirit,
Ascension,Banner Health,Baylor Scott White,Memorial Hermann,Houston Methodist,Emory Healthcare,
Duke Health,UPMC,Geisinger,Henry Ford Health,Corewell Health,Sanford Health,
Publix,Albertsons,Ahold Delhaize,Wegmans,HEB,Meijer,Hy-Vee,Sprouts,Whole Foods,Trader Joes,
Dollar General,Dollar Tree,Five Below,Ross Stores,TJX,Burlington Stores,Ulta Beauty,Sephora,
Bath & Body Works,Victorias Secret,Abercrombie,American Eagle,Urban Outfitters,Levi Strauss,
Ralph Lauren,PVH,Tapestry,Capri Holdings,Skechers,Crocs,Deckers,Wolverine Worldwide,Carters,
AutoZone,OReilly Automotive,Advance Auto Parts,Genuine Parts,Tractor Supply,Academy Sports,
Dicks Sporting Goods,REI,Petco,PetSmart,Chewy,Wayfair,Overstock,Williams-Sonoma,RH,Ikea,
Sherwin-Williams,PPG,Axalta,RPM International,Valspar,Masco,Mohawk Industries,Fortune Brands,
Stanley Black & Decker,Snap-on,Illinois Tool Works,Dover,Ingersoll Rand,Flowserve,Xylem,
Pentair,Watts Water,AO Smith,Trane Technologies,Carrier,Lennox,Johnson Controls,Otis,
Textron,Spirit AeroSystems,Howmet,Heico,TransDigm,Curtiss-Wright,Moog,Woodward,
Jacobs,AECOM,Fluor,KBR,Quanta Services,EMCOR,MasTec,Tetra Tech,Stantec,WSP,Arcadis,HDR,Burns McDonnell,
Kiewit,Turner Construction,Skanska,Bechtel,Whiting-Turner,DPR Construction,Gilbane,Suffolk,
Vulcan Materials,Martin Marietta,Nucor,Steel Dynamics,Cleveland-Cliffs,Alcoa,Freeport-McMoRan,
Newmont,Mosaic,Nutrien,Corteva,FMC Corporation,Albemarle,Celanese,Eastman Chemical,Dow,DuPont,
LyondellBasell,Westlake Chemical,Olin,Huntsman,Ashland,Avient,Cabot,
Ecolab,Sealed Air,Ball Corporation,Crown Holdings,Berry Global,Amcor,International Paper,WestRock,
Packaging Corporation,Graphic Packaging,Sonoco,Avery Dennison,
Marathon Petroleum,Phillips 66,Valero,Occidental Petroleum,Devon Energy,Diamondback Energy,EOG Resources,
Pioneer Natural Resources,Hess,Apache,Coterra,Chesapeake Energy,Williams Companies,Kinder Morgan,
ONEOK,Targa Resources,Cheniere Energy,Sempra,PG&E,Edison International,Xcel Energy,WEC Energy,
DTE Energy,Ameren,CenterPoint Energy,CMS Energy,Entergy,Evergy,PPL,PSEG,Eversource,Alliant Energy,
FirstEnergy,American Electric Power,Consolidated Edison,National Grid,Vistra,NRG Energy,Constellation Energy,
American Water,Essential Utilities,Waste Management,Republic Services,Clean Harbors,Stericycle,Casella,
Delta Dental,Guardian,Cigna Healthcare,
Marriott Vacations,Hyatt,Wyndham,Choice Hotels,IHG,Accor,MGM Resorts,Caesars Entertainment,
Wynn Resorts,Las Vegas Sands,Royal Caribbean,Carnival,Norwegian Cruise Line,Vail Resorts,
Live Nation,Endeavor,AMC Entertainment,Cinemark,IMAX,Lionsgate,AMC Networks,Fox Corporation,
News Corp,New York Times,Gannett,Hearst,Conde Nast,Vox Media,BuzzFeed,Axios,
Omnicom,Interpublic,Publicis,WPP,Dentsu,Stagwell,Criteo,Trade Desk,Magnite,PubMatic,DoubleVerify,
Integral Ad Science,LiveRamp,Nielsen,Comscore,Kantar,Ipsos,YouGov,Morning Consult,
Equifax,Experian,TransUnion,Dun & Bradstreet,CoStar,Verisk,Clarivate,RELX,Wolters Kluwer,Pearson,
Cengage,McGraw Hill,Houghton Mifflin,Scholastic,Chegg Services,Grand Canyon Education,Strayer,
Sodexo,Aramark,Compass Group,US Foods,Sysco,Performance Food Group,Gordon Food Service,
Cintas,UniFirst,ABM Industries,ISS Facility Services,Allied Universal,Securitas,Brinks,
Iron Mountain,Pitney Bowes,Xerox,Lexmark,Ricoh,Canon,Nikon,Panasonic,Hitachi,Toshiba,Fujitsu,NEC,
Ericsson,Nokia,Samsung,LG Electronics,Lenovo,ASUS,Acer,Logitech,Corsair,Razer,Sonos,Bose,Garmin,
Motorola Solutions,Zebra Technologies,Honeywell Aerospace,TE Connectivity,Amphenol,Corning,II-VI,
Coherent,Lumentum,Viavi,Keysight,National Instruments,Teradyne,Advantest,Onto Innovation,
Entegris,MKS Instruments,Brooks Automation,Axcelis,Veeco,Kulicke Soffa,Photronics,Amkor,
GlobalFoundries,TSMC,UMC,SK hynix,Kioxia,Infineon,STMicroelectronics,Renesas,Rohm,Skyworks,
Qorvo,Cirrus Logic,Silicon Labs,Lattice Semiconductor,Rambus,Synaptics,Ambarella,Allegro MicroSystems,
Diodes Incorporated,Vishay,Littelfuse,Wolfspeed,Power Integrations,MACOM,Semtech,Astera,
Splunk Technology,Dynatrace,New Relic,AppDynamics,Sumo,Chronosphere,Honeycomb,
Nutanix Cloud,Cohesity,Rubrik Security,Veeam,Commvault,Veritas,Barracuda,Sophos,Trellix,Trend Micro,
Proofpoint,Mimecast,Abnormal Security,KnowBe4,Netskope,Zscaler Cloud,Illumio,Claroty,Armis,Axonius,
Arctic Wolf,Huntress,Expel,ReliaQuest,Deepwatch,Recorded Future,Flashpoint,ZeroFox,Digital Shadows,
Coupa,Anaplan,Blackbaud,Bentley Systems,PTC,Dassault Systemes,Hexagon,Trimble,Altair,MathWorks,
Epicor,IFS,Unit4,Sage,Xero,BlackLine,Avalara,Vertex Inc,Bill.com,Ramp Business,Navan,TripActions,
Zuora,Chargebee,Recurly,Stripe Payments,Braintree,WePay,Toast Tab,Lightspeed,Shift4,Global Payments Inc,
Alliance Data,Bread Financial,Green Dot,Marqeta Inc,Payoneer Global,Flywire,AvidXchange,Billtrust,
Docker,GitHub,JFrog,CircleCI,Harness,Puppet,Chef,Ansible,Terraform,Pulumi,Render,Railway,Fly.io,
Supabase,Neon,Cockroach,Yugabyte,SingleStore,Couchbase,DataStax,Neo4j,InfluxData,Timescale,ClickHouse,
Starburst,Dremio,Firebolt,Imply,StreamNative,Materialize,dbt Labs,Astronomer,Prefect,Dagster,
Weights & Biases,Comet ML,Arize,Fiddler,Galileo,LangChain,LlamaIndex,Pinecone,Weaviate,Qdrant,Chroma,
Zilliz,Vespa,Elasticsearch,Algolia,Meilisearch,Typesense,Coveo,Lucidworks,
Twilio Segment,Amplitude Analytics,Mixpanel,Heap,FullStory,Hotjar,Contentsquare,Quantum Metric,
Braze Inc,Iterable Inc,Customer.io,Klaviyo Marketing,Attentive Mobile,Emarsys,Bloomreach,Optimizely,
VWO,LaunchDarkly Flags,Split Software,Statsig,Eppo,Amplitude Experiment,
Zoom Video,RingCentral,8x8,Five9,NICE,Genesys,Talkdesk,Dialpad,Vonage,Bandwidth,Sinch,
Asana Work,Monday.com,Smartsheet Inc,Wrike,Basecamp,Height,Linear,Shortcut,Aha,Productboard,
Miro Board,Figma Design,Canva Design,InVision,Framer,Webflow Inc,Wix,Squarespace Inc,Shopify,
BigCommerce,Magento,Salsify,Syndigo,Akeneo,commercetools,Fabric,Bolt,Fast,Shippo,ShipBob,Flexe,
Convoy,Uber Freight,Loadsmart,project44,FourKites,Samsara Fleet,Motive Technologies,KeepTruckin,
Trimble Transportation,Descartes,E2open,Blue Yonder,Kinaxis,o9 Solutions,Coupa Supply,Jaggaer,
`.split(/[,\n]/).map(s=>s.trim()).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);
