// 候选公司名单：美国科技与相关行业，用于探测各家官方招聘系统。
export const COMPANIES=`
Stripe,Figma,Anthropic,OpenAI,Notion,Ramp,Perplexity,Databricks,Discord,Reddit,Airbnb,Cloudflare,
Airtable,Asana,Atlassian,Amplitude,Affirm,Alchemy,Anduril,AppLovin,Arc,Attentive,Auth0,Automattic,
Benchling,BetterUp,Bill,Bitgo,Blend,Block,Box,Braze,Brex,Bungie,Calendly,Canva,Carta,Chainalysis,
Checkr,Chime,Cribl,Clari,ClickUp,Clover,Coalition,Cohere,Coinbase,Confluent,Contentful,Coursera,
Cockroach Labs,Course Hero,Crowdstrike,Cruise,Datadog,Dave,Deel,Descript,DigitalOcean,Discourse,
DoorDash,Doximity,Drata,Dropbox,Duolingo,Dutchie,Elastic,Envoy,Etsy,Evernote,Expensify,Faire,
Fastly,Fivetran,Flexport,Forter,Foursquare,Front,Gem,Getty Images,Gitlab,Glean,Glassdoor,Gong,
Grafana Labs,Grammarly,Greenhouse,Gusto,HashiCorp,Headway,Hinge,Hopper,Houzz,Hugging Face,Human Interest,
IXL Learning,Iterable,Instacart,Ironclad,Jane Street,Jerry,Justworks,Kandji,Klaviyo,Kraken,Lattice,
LaunchDarkly,Lime,LinkedIn,Lucid,Lyft,Mapbox,Marqeta,Match Group,Medallia,Mercury,Miro,Modern Treasury,
MongoDB,Motive,Mozilla,Narvar,Netlify,Newfront,Nextdoor,Nerdwallet,Niantic,Nuro,Nylas,Oscar Health,
Outreach,Palantir,PagerDuty,Pave,Peloton,Pendo,Persona,Pinterest,Plaid,Planet,PlanetScale,Postman,
Postscript,Quora,Qualtrics,Quizlet,Rakuten,Rappi,Redis,Remitly,Retool,Rippling,Robinhood,Roblox,Roku,
Rubrik,Samsara,Scale AI,Sentry,ServiceTitan,Shield AI,Sierra,SigFig,Signal,Sift,Skydio,Slack,Smartsheet,
Snyk,SoFi,SonderMind,Sourcegraph,SpaceX,Splunk,SpotOn,Spotify,Sprinklr,Square,Squarespace,Stord,
StubHub,Sumo Logic,Superhuman,Sysdig,Tanium,Teachable,Tealium,Tempus,Thumbtack,TikTok,Tinder,Toast,
Tripadvisor,Twilio,Twitch,Udemy,Unity,Upstart,Upwork,Vanta,Veeva,Verkada,Vercel,Via,Vimeo,Wealthfront,
Webflow,WeWork,Whatnot,Wish,Wiz,Workato,Yelp,Zapier,Zendesk,Zscaler,Zoox,Zocdoc,
Nvidia,Adobe,Salesforce,Intel,Cisco,PayPal,ServiceNow,Workday,Dell,HP,Qualcomm,Broadcom,AMD,
Oracle,IBM,SAP,VMware,Nutanix,Pure Storage,NetApp,Juniper Networks,Arista Networks,F5,Akamai,
Texas Instruments,Analog Devices,Microchip Technology,ON Semiconductor,NXP Semiconductors,Lam Research,
Applied Materials,KLA,Micron,Marvell,Western Digital,Seagate,Synopsys,Cadence,Ansys,Autodesk,
Intuit,Uber,Lucid Motors,Rivian,Tesla,Waymo,Wayfair,Zoom,DocuSign,Dropbox,eBay,Expedia,Zillow,
Snap,Netflix,Pinterest,Yahoo,Comcast,Charter Communications,Verizon,AT&T,T-Mobile,Warner Bros Discovery,
Paramount,Sony,Electronic Arts,Activision Blizzard,Riot Games,Epic Games,Take-Two Interactive,Zynga,
Walmart,Target,Costco,Kroger,Home Depot,Lowes,Best Buy,Nordstrom,Gap,Nike,Starbucks,Chipotle,
McDonalds,Marriott,Hilton,Delta Air Lines,United Airlines,American Airlines,Southwest Airlines,
JPMorgan Chase,Goldman Sachs,Morgan Stanley,Bank of America,Wells Fargo,Citi,Capital One,American Express,
Charles Schwab,Fidelity,BlackRock,Vanguard,State Street,PNC,Truist,US Bank,Discover,Synchrony,
Visa,Mastercard,Fiserv,FIS,Global Payments,Nasdaq,CME Group,Intercontinental Exchange,S&P Global,
Moodys,MSCI,FactSet,Bloomberg,Thomson Reuters,Gartner,McKinsey,Bain,Boston Consulting Group,
Deloitte,PwC,EY,KPMG,Accenture,Cognizant,Infosys,Wipro,Capgemini,Booz Allen Hamilton,Leidos,
Lockheed Martin,Northrop Grumman,Raytheon,General Dynamics,Boeing,L3Harris,BAE Systems,Honeywell,
GE Aerospace,GE HealthCare,Emerson,Rockwell Automation,Eaton,Parker Hannifin,Caterpillar,Deere,
3M,Danaher,Thermo Fisher Scientific,Agilent,Illumina,Bio-Rad,Waters,PerkinElmer,Roche,Genentech,
Pfizer,Merck,Bristol Myers Squibb,Eli Lilly,AbbVie,Amgen,Gilead,Biogen,Regeneron,Vertex,Moderna,
Johnson & Johnson,Abbott,Medtronic,Stryker,Boston Scientific,Becton Dickinson,Baxter,Zimmer Biomet,
Intuitive Surgical,Edwards Lifesciences,Hologic,ResMed,Dexcom,Insulet,GE Vernova,Siemens,Philips,
UnitedHealth Group,CVS Health,Cigna,Elevance Health,Humana,Centene,HCA Healthcare,Kaiser Permanente,
Procter & Gamble,Unilever,PepsiCo,Coca-Cola,General Mills,Kellogg,Kraft Heinz,Mondelez,Hershey,
Colgate-Palmolive,Estee Lauder,Clorox,Church & Dwight,Tyson Foods,Conagra,Campbell Soup,
ExxonMobil,Chevron,ConocoPhillips,Schlumberger,Halliburton,Baker Hughes,NextEra Energy,Duke Energy,
Dominion Energy,Exelon,Southern Company,AES,First Solar,Enphase Energy,SolarEdge,Sunrun,
FedEx,UPS,XPO,CH Robinson,Union Pacific,CSX,Norfolk Southern,Ryder,Penske,
Ford,General Motors,Stellantis,Toyota,Honda,BMW,Mercedes-Benz,Volkswagen,Cummins,PACCAR,
Equinix,Digital Realty,CBRE,JLL,Cushman & Wakefield,WeWork,Compass,Redfin,Opendoor,Zillow Group,
Peloton,Lululemon,Under Armour,Adidas,Puma,New Balance,Columbia Sportswear,VF Corporation,
Yum Brands,Domino's,Papa Johns,Wendys,Darden,Bloomin Brands,Cheesecake Factory,
Robert Half,ADP,Paychex,Paycom,Paylocity,Ceridian,UKG,TriNet,Insperity,
Palo Alto Networks,Fortinet,Check Point,SentinelOne,Rapid7,Tenable,Qualys,Varonis,Okta,CyberArk,
Cloudera,Snowflake,Teradata,Informatica,Talend,Alteryx,Domo,Tableau,Looker,Sisense,ThoughtSpot,
Twitter,Meta,Google,Apple,Amazon,Microsoft,Airbnb,Lyft,DoorDash,Instacart,Grubhub,Postmates,
Blue Origin,Relativity Space,Rocket Lab,Astra,Firefly Aerospace,Sierra Space,Planet Labs,Maxar,
Applied Intuition,Aurora,Motional,Zoox,Argo AI,Pony AI,WeRide,TuSimple,Kodiak Robotics,
Figure AI,Boston Dynamics,Agility Robotics,Physical Intelligence,Skild AI,Covariant,
Mistral AI,Runway,ElevenLabs,Character AI,Adept,Inflection AI,Together AI,Fireworks AI,Groq,Cerebras,
SambaNova,Graphcore,Tenstorrent,Lightmatter,Astera Labs,Ampere Computing,SiFive,Rivos,
Databento,Two Sigma,Citadel,Jump Trading,DRW,IMC Trading,Optiver,SIG,Hudson River Trading,
Point72,Millennium,Bridgewater,AQR,Balyasny,Squarepoint,XTX Markets,Old Mission,Akuna Capital,
Duolingo,Khan Academy,Chegg,Udacity,Skillsoft,2U,Guild Education,Newsela,
Carvana,CarGurus,Cars.com,Vroom,Shift,TrueCar,AutoNation,CarMax,
Affirm,Afterpay,Klarna,Marqeta,Adyen,Checkout.com,Payoneer,Remitly,Wise,Revolut,Nubank,
Oportun,LendingClub,Avant,Prosper,Best Egg,Achieve,Figure,Blend Labs,
Flatiron Health,Komodo Health,Included Health,Ro,Hims,Cedar,Olive,Notable Health,
Zocdoc,Headspace,Calm,Noom,Whoop,Oura,Peloton Interactive,Strava,AllTrails,
Life360,Nextdoor,Bumble,Grindr,Hinge Health,Talkspace,BetterHelp,Lyra Health,Spring Health,
Benchling,Ginkgo Bioworks,Recursion,Insitro,Tempus AI,Freenome,Grail,Guardant Health,Natera,
23andMe,Color Health,Invitae,Myriad Genetics,Exact Sciences,
`.split(/[,\n]/).map(s=>s.trim()).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);
export function slugs(name){
 const base=name.toLowerCase().replace(/&/g,'and').replace(/[.']/g,'');
 const compact=base.replace(/[^a-z0-9]/g,'');
 const hyphen=base.replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 const first=compact.replace(/(inc|corp|corporation|company|group|labs|technologies|holdings)$/,'');
 return [compact,hyphen,first].filter((v,i,a)=>v&&a.indexOf(v)===i);
}
